### ISSUE TITLE
 checkpoint

### ISSUE THREAD

**Issue by JunMa11** [alibaba-damo-academy/pixel-lesion-patient-network#1]
Hi @viggin ,

Thanks for sharing the awesome work!

Would it be possible for you to share the trained model checkpoint and the corresponding inference code?

**Comment by viggin** [comment]
Hi Jun,
I'm sorry, the trained model cannot be released due to intellectual property issues. The inference code has been included in the repo. You can modify the config files to easily infer. Thanks!
