### ISSUE TITLE
there is no file named 'UNet_plan_and_preprocess'

### ISSUE THREAD

**Issue by xiaohuji** [alibaba-damo-academy/pixel-lesion-patient-network#2]
i only find 'nnUNet_plan_and_preprocess.py'

**Comment by viggin** [comment]
Please see the readme in https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1
After installing nnunet, you can run the command named UNet_plan_and_preprocess in bash, which is defined in nnUNet_plan_and_preprocess.py

**Comment by xiaohuji** [comment]
in setup.py, i only find 'nnUNet_plan_and_preprocess = nnunet.experiment_planning.nnUNet_plan_and_preprocess:main', i cannot find command about: UNet_plan_and_preprocess

**Comment by xiaohuji** [comment]
> Please see the readme in https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1 After installing nnunet, you can run the command named UNet_plan_and_preprocess in bash, which is defined in nnUNet_plan_and_preprocess.py

in setup.py, i only find 'nnUNet_plan_and_preprocess = nnunet.experiment_planning.nnUNet_plan_and_preprocess:main', i cannot find command about: UNet_plan_and_preprocess

**Comment by xiaohuji** [comment]
thanks for your contribution :), running 'nnUNet_plan_and_preprocess -t XXX -pl2d None' could solve this problem, for this issue i really want to ensure if there is a file named UNet_plan_and_preprocess.py instead of nnUNet_plan_and_preprocess.py
